version: "2.4"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.25
    volumes:
      - /opt/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: localhost
    environment:
      MYSQL_DATABASE: 'bd_test'
      MYSQL_USER: 'user_bd'
      MYSQL_PASSWORD: 'password_user_bd'
      MYSQL_ROOT_PASSWORD: 'replace_me'